// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWfwjNDY_Z2JbtCCZ3n0EJYmHS3DLVrio',
    appId: '1:639021095465:web:9310863149c23477d2da38',
    messagingSenderId: '639021095465',
    projectId: 'mini-project-7a4a9',
    authDomain: 'mini-project-7a4a9.firebaseapp.com',
    databaseURL: 'https://mini-project-7a4a9-default-rtdb.firebaseio.com',
    storageBucket: 'mini-project-7a4a9.appspot.com',
    measurementId: 'G-RMT00XZ2KH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSP8PWqHsDEsvx06M5QkH-JUmsfZvIRYI',
    appId: '1:639021095465:android:cc98e9303ccce840d2da38',
    messagingSenderId: '639021095465',
    projectId: 'mini-project-7a4a9',
    databaseURL: 'https://mini-project-7a4a9-default-rtdb.firebaseio.com',
    storageBucket: 'mini-project-7a4a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUaGHKE6ElQfKOiZJVr4oKC3h_ZwGIp14',
    appId: '1:639021095465:ios:261152f8b6c2df52d2da38',
    messagingSenderId: '639021095465',
    projectId: 'mini-project-7a4a9',
    databaseURL: 'https://mini-project-7a4a9-default-rtdb.firebaseio.com',
    storageBucket: 'mini-project-7a4a9.appspot.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUaGHKE6ElQfKOiZJVr4oKC3h_ZwGIp14',
    appId: '1:639021095465:ios:261152f8b6c2df52d2da38',
    messagingSenderId: '639021095465',
    projectId: 'mini-project-7a4a9',
    databaseURL: 'https://mini-project-7a4a9-default-rtdb.firebaseio.com',
    storageBucket: 'mini-project-7a4a9.appspot.com',
    iosBundleId: 'com.example.test',
  );
}
